version: '2'

services:
    bob:
        build: ./bob
        environment:
            - CTF_FLAG=FOOBAR

    alice:
        build: ./alice
        depends_on:
            - bob
        environment:
            - CTF_FLAG=FOOBAR

networks:
    default:
        internal: true
