version: '2.1'

services:
    bob:
        build: ./bob
        image: naumachia/example/bob
        environment:
            - CTF_FLAG=FOOBAR

    alice:
        build: ./alice
        image: naumachia/example/alice
        depends_on:
            - bob
        environment:
            - CTF_FLAG=FOOBAR

networks:
    default:
        internal: true
