version: '2'

services:
    eve:
        build: ./eve/build
        networks:
            default:
        stdin_open: true
        tty: true
        volumes:
            - ./eve/config:/config
        privileged: true

    openvpn:
        build:
            context: ./openvpn/build
            args:
                - OVPN_REPO_URL
                - OVPN_REPO_BRANCH
        depends_on:
            - redis
        volumes:
            - ./openvpn/config:/etc/openvpn
            - /var/run/docker/netns/default:/var/run/netns/host
            - ./openvpn/build/scripts:/scripts
        networks:
            default:
            internal:
        ports:
            - "1194:1194/udp"
        cap_add:
            - NET_ADMIN
        environment:
            - REDIS_HOSTNAME
            - REDIS_PORT
            - REDIS_DB
            - REDIS_PASSWORD

    redis:
        image: "redis:alpine"
        networks:
            internal:
                aliases:
                    - "$REDIS_HOSTNAME"
        volumes:
            - ./redis/config:/usr/local/etc/redis
        command: [redis-server, /usr/local/etc/redis/redis.conf]

    cluster-manager:
        build: ./cluster-manager/build
        depends_on:
            - redis
        networks: 
            internal:
        volumes:
            - ./cluster-manager/app:/app
            - ./challenges:/challenges
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/run/docker/netns/default:/var/run/netns/host
        command: [python3, /app/cluster-manager.py]
        environment:
            - REDIS_HOSTNAME
            - REDIS_PORT
            - REDIS_DB
            - REDIS_PASSWORD
        privileged: true
        restart: always


networks:
    internal:
        internal: true
