version: '2'

services:
    eve:
        build: ./eve/build
        networks:
            user:
        stdin_open: true
        tty: true
        volumes:
            - ./eve/config:/config
        privileged: true

    openvpn:
        build: ./openvpn/build
        volumes:
            - ./openvpn/config:/etc/openvpn
            - ./openvpn/scripts:/nam
        networks:
            chal:
                ipv4_address: 10.0.100.10
            user:
                ipv4_address: 10.0.200.10
            internal:
                ipv4_address: 10.0.50.10
        ports:
            - "1194:1194/udp"
        cap_add:
            - NET_ADMIN
        environment:
            - REDIS_HOSTNAME
            - NAM_ADDR_KEY
            - NAM_CN_KEY
        links:
            - "redis:${REDIS_HOSTNAME}"

    redis:
        image: "redis:alpine"
        networks:
            internal:
        volumes:
            - ./redis/config:/usr/local/etc/redis
        command: [redis-server, /usr/local/etc/redis/redis.conf]

    cluster-manager:
        image: "python:alpine"
        networks: 
            internal:
        volumes:
            - ./cluster-manager/app:/app
        command: [python, /app/cluster-manager.py]

networks:
    chal:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.100.0/24
                  ip_range: 10.0.100.128/25
                  gateway: 10.0.100.1
    user:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.200.0/24
                  ip_range: 10.0.200.128/25
                  gateway: 10.0.200.1

    internal:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.50.0/24
                  ip_range: 10.0.50.128/25
                  gateway: 10.0.50.1
