version: '2'

services:
    eve:
        build: ./eve/build
        networks:
            default:
        stdin_open: true
        tty: true
        volumes:
            - ./eve/config:/config
        privileged: true

    openvpn:
        build: ./openvpn/build
        volumes:
            - ./openvpn/config:/etc/openvpn
            - ./openvpn/scripts:/nam
        networks:
            chal:
                ipv4_address: 10.0.100.10
            default:
                ipv4_address: 10.0.200.10
            internal:
                ipv4_address: 10.0.50.10
        ports:
            - "1194:1194/udp"
        cap_add:
            - NET_ADMIN
        environment:
            - REDIS_HOSTNAME
            - REDIS_PORT
            - REDIS_DB
            - BRIDGED_IP=10.0.100.10

    redis:
        image: "redis:alpine"
        networks:
            internal:
                ipv4_address: 10.0.50.20
                aliases:
                    - "$REDIS_HOSTNAME"
        volumes:
            - ./redis/config:/usr/local/etc/redis
        command: [redis-server, /usr/local/etc/redis/redis.conf]

    cluster-manager:
        build: ./cluster-manager/build
        networks: 
            internal:
        volumes:
            - ./cluster-manager/app:/app
            - ./challenges:/challenges
            - /var/run/docker.sock:/var/run/docker.sock
        command: [python, /app/cluster-manager.py]
        environment:
            - REDIS_HOSTNAME
            - NAM_ADDR_KEY
            - NAM_CN_KEY


networks:
    chal:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.100.0/24
                  ip_range: 10.0.100.128/25
                  gateway: 10.0.100.1
        internal: true

    default:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.200.0/24
                  ip_range: 10.0.200.128/25
                  gateway: 10.0.200.1

    internal:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.50.0/24
                  ip_range: 10.0.50.128/25
                  gateway: 10.0.50.1
        internal: true
