version: '2'

services:
    eve:
        build: ./eve/build
        networks:
            user:
        stdin_open: true
        tty: true
        volumes:
            - ./eve/config:/config
        privileged: true

    openvpn:
        build: ./openvpn/build
        volumes:
            - ./openvpn/config:/etc/openvpn
        networks:
            chal:
            user:
            internal:
        ports:
            - "1194:1194/udp"
        cap_add:
            - NET_ADMIN

    redis:
        image: "redis:alpine"
        networks:
            internal:

networks:
    chal:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.100.0/24
                  ip_range: 10.0.100.128/25
                  gateway: 10.0.100.1
    user:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.200.0/24
                  ip_range: 10.0.200.128/25
                  gateway: 10.0.200.1

    internal:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.200.0/24
                  ip_range: 10.0.200.128/25
                  gateway: 10.0.200.1
