version: '2'

services:
    bob:
        build: ./bob
        environment:
            - CTF_FLAG=67afB27edB18Fe33
        cap_add:
            - NET_ADMIN

    alice:
        build: ./alice
        depends_on:
            - bob
        environment:
            - CTF_FLAG=67afB27edB18Fe33
        cap_add:
            - NET_ADMIN

networks:
    default:
        internal: true
