version: '2'

services:
    eve:
        image: ubuntu:16.04
        networks:
            user:
                ipv4_address: 10.0.200.10

    bob:
        image: ubuntu:16.04
        networks:
            chal:
                ipv4_address: 10.0.100.30

    alice:
        image: ubuntu:16.04
        networks:
            chal:
                ipv4_address: 10.0.100.20

    openvpn-as:
        image: linuxserver/openvpn-as
        volumes:
            - ./openvpn-as/server-conf:/config
        networks:
            chal:
                ipv4_address: 10.0.100.10
        privileged: true

networks:
    chal:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.100.0/24
                  ip_range: 10.0.100.128/23
                  gateway: 10.0.100.1
    user:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.200.0/24
                  ip_range: 10.0.200.128/23
                  gateway: 10.0.200.1
