version: '2'

services:
    eve:
        build: ./eve
        networks:
            user:
                ipv4_address: 10.0.200.40
        stdin_open: true
        tty: true
        volumes:
            - ./eve/config:/config
        cap_add:
            - NET_ADMIN

    bob:
        image: ubuntu:latest
        networks:
            chal:
                ipv4_address: 10.0.100.30
        stdin_open: true
        tty: true

    alice:
        image: ubuntu:latest
        networks:
            chal:
                ipv4_address: 10.0.100.20
        stdin_open: true
        tty: true

    openvpn:
        build: ./openvpn
        volumes:
            - ./openvpn/data:/etc/openvpn
        networks:
            chal:
                ipv4_address: 10.0.100.10
            user:
                ipv4_address: 10.0.200.10
        ports:
            - "1194:1194/udp"
        cap_add:
            - NET_ADMIN

networks:
    chal:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.100.0/24
                  ip_range: 10.0.100.128/23
                  gateway: 10.0.100.1
    user:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.200.0/24
                  ip_range: 10.0.200.128/23
                  gateway: 10.0.200.1
