version: '2'

services:
    eve:
        build: ./eve/build
        networks:
            user:
                ipv4_address: 10.0.200.40
        stdin_open: true
        tty: true
        volumes:
            - ./eve/config:/config
        privileged: true

    bob:
        build: ./bob
        networks:
            chal:
                ipv4_address: 10.0.100.30
        environment:
            - CTF_FLAG=67afB27edB18Fe33

    alice:
        build: ./alice
        networks:
            chal:
                ipv4_address: 10.0.100.20
        depends_on:
            - bob
        environment:
            - CTF_FLAG=67afB27edB18Fe33

    openvpn:
        build: ./openvpn/build
        volumes:
            - ./openvpn/config:/etc/openvpn
        networks:
            chal:
                ipv4_address: 10.0.100.10
            user:
                ipv4_address: 10.0.200.10
        ports:
            - "1194:1194/udp"
        cap_add:
            - NET_ADMIN

networks:
    chal:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.100.0/24
                  ip_range: 10.0.100.128/23
                  gateway: 10.0.100.1
    user:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.200.0/24
                  ip_range: 10.0.200.128/23
                  gateway: 10.0.200.1
